version: '3'

services:
  croni:
    image: atareao/croni:v1.1
    container_name: croni_for_bmc
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./crontab:/crontab
    env_file:
      - bmc_prod.env
  bmc:
    build: ./
    image: atareao/bmc
    container_name: bmc
    restart: unless-stopped
    networks:
      - internal
      - proxy
    volumes:
      - ./database:/app/database
      - ./templates:/app/templates
    env_file:
      - bmc_prod.env
    ports:
      - 8001:8000
    labels:
      - traefik.enable=true
      - traefik.http.services.bmc.loadbalancer.server.port=8000
      - traefik.http.routers.bmc.entrypoints=http
      - traefik.http.routers.bmc.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.bmc-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.bmc.middlewares=expulsabot-https-redirect
      - traefik.http.routers.bmc-secure.entrypoints=https
      - traefik.http.routers.bmc-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.bmc-secure.tls=true
      - traefik.http.routers.bmc-secure.tls.certresolver=myresolver

networks:
  internal:
  proxy:
    external: true

